export { Navbar } from './Navbar/Navbar';
export { Footer } from './Footer/Footer';
export { Sort } from './Sort/Sort';
export { CarouselNews } from './CarouselNews/CarouselNews';
export { CarouselNewProduct } from './CarouselNewProduct/CarouselNewProduct';
export { DiscountNews } from './DiscountNews/DiscountNews';
export { AboutOurProduct } from './AboutOurProduct/AboutOurProduct';
export { Brands } from './Brands/Brands';
export { CarouselManagers } from './CarouselManagers/CarouselManagers';